glenn-syj/more-effective-java

chapter_02/item01_육민우_정적-팩터리-메서드-반환타입의-유연성.md
=> [MEJ-001] Docs: item01 정적 팩터리 메서드 반환타입의 유연성

chapter_02/item01_육민우_정적-팩터리-메서드-반환타입의-유연성.md
item01 정적 팩터리 메서드 반환타입의 유연성 커밋 다시 제출합니다.
=> [MEJ-001] Docs: item01 정적-팩터리-메서드-반환타입의-유연성 재제출

chapter_03/item10_육예진_equals-메서드-재정의-지양에-관해.md
=> [MEJ-003] Docs: item10 equals 메서드 재정의 지양에 관해

chapter_02/item07_송창용_메모리-관리-방법과-WeakHashmap에-대해.md
3주차 작성글 제출합니다.
다음 제출 시에는 예기치 못한 사고가 발생하더라도 기한을 넘기지 않도록 하겠습니다.
양식과 내용에 올바르지 못한 부분이나 부족한 곳이 존재하는지 확인 부탁드립니다.
=> [MEJ-003] Docs: item07 메모리 관리 방법과 WeakHashMap 관련 글 작성

chapter_03/item12_유서현_toString()-메서드의-일반-규약과-파싱(parsing).md.md
3주차에는 아이템 12를 읽고 글을 작성해 보았습니다.
=> [MEJ-003] Docs: item12 toString() 메서드의 일반 규약과 파싱(parsing) 글 작성

chapter_03/item14_육예진_compareTo-메서드의-객체-동등성-비교.md
compareTo, equals 메서드와  HashSet, TreeSet 등 자료구조의 관계에 대해 탐구해보았습니다.
글 양식 및 내용 검토 부탁드립니다.
=> [MEJ-004] Docs: item14 compareTo 메서드의 객체 동등성 비교에 관한 글 작성

chapter_04/item16_신승호_package-private-와-중첩 클래스를-중점으로.md
package-private 와 중첩 클래스 관한 글 작성하였습니다.
글 양식 및 내용 검토 부탁드립니다.
=> [MEJ-004] Docs: item16 package-private 와 중첩 클래스 관한 글 작성

chapter_04/item20_유서현_다중-상속-관계에서의-다이아몬드-문제.md
5주차에는 item 20을 읽고 다이아몬드 문제에 대한 심화 탐구를 진행해 보았습니다. 이번주도 다들 고생 많으셨습니다!
=> [MEJ-005] Docs: item20 다중 상속 관계에서의 다이아몬드 문제에 대한 글 작성

chapter_05/item27_송창용_SuppressWarnings-애노테이션에-대해.md
6주차 item27에 대한 md 파일 제출합니다.
형식과 내용에 문제가 없는지 확인 부탁드립니다.
=> [MEJ-006] Docs: item27 SuppressWarnings 애노테이션 관련 글 작성

chapter_05/item29_손영준_ArrayList-클래스를-통한-제네릭-심화-탐구.md
- 실체화 불가 타입을 제네릭으로 이용하는 방식 요약
- ArrayList가 배열 및 제네릭을 이용하는 방식 탐구
=> [MEJ-006] Docs: item29 ArrayList를통한제네릭 클래스 탐구 글 작성

chapter_05/item30_육예진_제네릭_싱글턴-팩터리-메서드란.md
제네릭 메서드를 사용한 제네릭 싱글턴 팩터리에 대해 공부해보았습니다.
=> [MEJ-007] Docs: item30 제네릭 싱글턴 팩터리 메서드에 관한 글 작성

chapter_06/item33_송창용_타입-토큰에-대해.md
특히 어려운 개념에 대해 공부하다보니 만족스럽지 못한 글을 작성하였습니다.
추후, 해당 개념에 대해 공부하여 정리해보도록 하겠습니다.
제출물에 대해 형식과 내용이 올바르지 않은 부분이 있는지 확인 부탁드립니다.
=> [MEJ-007] Docs: item33 타입 토큰에 관한 글 작성

chapter_05/item32_손영준_제네릭과-가변-인자에-대한-심화-탐구.md
- item32 내용 관련 코드
- 가변인자 Varargs의 개념
=> [MEJ-007] Docs: item32 제네릭과 가변인자에 대한 글 작성

chapter_06/item34_송창용_열거-타입이란-무엇인가.md
8주차 글 제출합니다.
내용상의 미흡한 점이나 올바르지 않은 형식이 있는지 확인 부탁드립니다.
=> [MEJ-008] Docs: item34 열거 타입에 대한 글 작성

chapter_06/item37_육예진_EnumMap의-내부구현방식에-대해.md
=> [MEJ-008] Docs: item37 EnumMap 내부구현방식에 대한 글 작성

chapter_06/item36_손영준_EnumSet과-구현체-심화-탐구.md
- done: enumset의 추가적인 속성
- done: RegularEnumSet, JumboEnumSet 탐구
=> [MEJ-008] Docs: Enumset과 구현체 심화 탐구

chapter_06/item38_송창용_확장-가능한-열거-타입에-대한-이해.md
한 부분에 대하여 많은 시간을 소모하다보니 다른 탐구사항에 대해서는 조사하지 못하였습니다.
이후, 추가적으로 조사를 진행 후 갱신하도록 하겠습니다.
=> [MEJ-009] Docs: 확장 가능한 열거 타입에 대한 글 작성

chapter_06/item40_육예진_Override-적용-여부의-차이에-대해.md
@Override 애너테이션 적용여부에 대해 간단한 실험을 진행했습니다.
=> [MEJ-009] Docs: item40 @Override 애너테이션 적용여부에 따른 차이에 관한 글 작성

chapter_07/item45_육예진_Stream-API-처리구조에-대한-이해.md
=> [MEJ-010] Docs: item45 스트림 처리구조에 관한 글 작성

chapter_07/item44_송창용_서로-다른-함수형-인터페이스를-받는-메서드들에-대해.md
내용과 형식에 올바르지 않은 곳이 있는지 확인 부탁드립니다.
=> [MEJ-010] Docs: item44 함수형 인터페이스를 받는 메서드에 관한 글작성

chapter_07/item43_육민우_메서드-참조-방식의-특징-및-장단점에-대한-고찰.md
함수 객체 방식부터 메서드 참조 방식에 이르기까지 각각의 과정에 대해 탐구하며 이해하는 방향으로 작성했습니다. 
늦게 커밋에서 죄송합니다.
=> [MEJ-010] Docs: item43 메서드 참조 방식의 특징 및 장단점에 대한 고찰에 관한 글 작성

chapter_08/item49_육민우_사용자-정의-예외를-통한-매개변수-유효성-검사.md
=> [MEJ-011] Docs: item49 사용자 정의 예외를 통한 매개변수 유효성 검사

chapter_07/item48_송창용_parallel-메서드에-대해.md
item48 제출합니다.
형식과 내용이 올바른지 확인 부탁드립니다.
=> [MEJ-011] Docs: item48 parallel 메서드에 대해

chapter_08/item53_육민우_자바에서-가변인수-메서드의-활용-예시.md
자바에서 가변인수 메서드의 활용 예시로 3가지 사례를 들며 알아보는 것을 탐구 주제로 선정하였습니다. 
보충 및 수정해야할 부분이 있으면 고치겠습니다.
=> [MEJ-012] Docs: item53 자바에서 가변인수 메서드의 활용 예시에 관한 글 작성

chapter_08/item51_육예진_매개변수-개수-조정-방법에-대해.md
메서드의 매개변수를 가능한 적게 유지하는 방법론에 대해 간단한 예시 코드를 작성하여 탐구해보았습니다.
=> [MEJ-012] Docs: item51 메서드 매개변수 개수 조정 방법에 대한 글 작성

chapter_08/item52_송창용_부정확한-메서드-참조와-적용-가능성-테스트에-대해.md
기한을 지키지 못해 죄송합니다.
형식과 내용에 올바르지 못한 부분이 있는지 확인 부탁드립니다.
=> [MEJ-012] Docs: item52 부정확한 메서드 참조와 적용 테스트에 대한 글 작성

chapter_08/item54_육민우_API-반환값과-성능-향상에-대한-고찰.md
=> [MEJ-013] Docs: item54 API 반환값과 성능 향상에 대한 고찰에 대한 글 작성
